-- Initial schema per DATABASE_DIAGRAM.md.
-- Reference: difficulty, states, review_policies, topics.
-- Operational: users, tasks, task_topics, user_tasks.
-- Reporting: user_reviews.

-- ============ Reference tables ============

CREATE TABLE difficulty (
    id      INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    level   VARCHAR(32) NOT NULL UNIQUE
);

CREATE TABLE states (
    id      INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code    VARCHAR(32) NOT NULL UNIQUE,
    label   VARCHAR(64) NOT NULL
);

-- Interval policy per review outcome (1:1 with states).
CREATE TABLE review_policies (
    state_id            INT PRIMARY KEY REFERENCES states (id) ON DELETE CASCADE,
    base_interval_days  INT  NOT NULL CHECK (base_interval_days > 0),
    growth_factor       REAL NOT NULL CHECK (growth_factor > 0),
    max_interval_days   INT  NOT NULL CHECK (max_interval_days > 0),
    is_active           BOOLEAN NOT NULL DEFAULT TRUE,
    CHECK (max_interval_days >= base_interval_days)
);

CREATE TABLE topics (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name        VARCHAR(128) NOT NULL UNIQUE,
    slug        VARCHAR(128) NOT NULL UNIQUE,
    created_at  TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- ============ Operational tables ============

CREATE TABLE users (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email       VARCHAR(320) NOT NULL UNIQUE,
    pass_hash   VARCHAR(255) NOT NULL,
    name        VARCHAR(128) NOT NULL,
    created_at  TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at  TIMESTAMPTZ NOT NULL DEFAULT now(),
    CHECK (position('@' in email) > 1)
);

-- Shared problem cards; identity_key is the deduplication key.
CREATE TABLE tasks (
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    identity_key        VARCHAR(255) NOT NULL UNIQUE,
    source_type         VARCHAR(32)  NOT NULL,
    source_problem_id   VARCHAR(128) NOT NULL,
    title               VARCHAR(512) NOT NULL,
    description         TEXT,
    link                VARCHAR(1024),
    difficulty_id       INT NOT NULL REFERENCES difficulty (id),
    created_at          TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at          TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE task_topics (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    task_id     BIGINT NOT NULL REFERENCES tasks (id) ON DELETE CASCADE,
    topic_id    BIGINT NOT NULL REFERENCES topics (id) ON DELETE CASCADE,
    created_at  TIMESTAMPTZ NOT NULL DEFAULT now(),
    UNIQUE (task_id, topic_id)
);

-- User's tracking state for a shared task.
CREATE TABLE user_tasks (
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id             BIGINT NOT NULL REFERENCES users (id) ON DELETE CASCADE,
    task_id             BIGINT NOT NULL REFERENCES tasks (id) ON DELETE CASCADE,
    current_state_id    INT NOT NULL REFERENCES states (id),
    last_review_date    DATE,
    next_review_date    DATE,
    user_notes          TEXT,
    created_at          TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at          TIMESTAMPTZ NOT NULL DEFAULT now(),
    UNIQUE (user_id, task_id)
);

CREATE INDEX idx_user_tasks_next_review ON user_tasks (user_id, next_review_date);

-- ============ Reporting table ============

CREATE TABLE user_reviews (
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_task_id        BIGINT NOT NULL REFERENCES user_tasks (id) ON DELETE CASCADE,
    state_id            INT NOT NULL REFERENCES states (id),
    reviewed_at         TIMESTAMPTZ NOT NULL DEFAULT now(),
    interval_days       INT NOT NULL CHECK (interval_days > 0),
    next_review_date    DATE NOT NULL,
    review_text         TEXT,
    created_at          TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX idx_user_reviews_user_task ON user_reviews (user_task_id, reviewed_at);

-- ============ Reference seed data ============

INSERT INTO difficulty (level) VALUES ('EASY'), ('MEDIUM'), ('HARD');

-- Review outcomes per BACKEND_FRONTEND_CONTRACT.md (forgot / partial / remember).
INSERT INTO states (code, label) VALUES
    ('FORGOT',  'Forgot'),
    ('PARTIAL', 'Partial'),
    ('REMEMBER','Remember');

INSERT INTO review_policies (state_id, base_interval_days, growth_factor, max_interval_days) VALUES
    ((SELECT id FROM states WHERE code = 'FORGOT'),  1, 1.0,  1),
    ((SELECT id FROM states WHERE code = 'PARTIAL'), 1, 1.0, 30),
    ((SELECT id FROM states WHERE code = 'REMEMBER'),2, 2.0, 90);
