-- Stage 6: per-user settings, named review-policy presets, account data extensions.

-- Named presets of interval policies (per review outcome). The built-in
-- 'standard' preset mirrors the global V1 review_policies values.
CREATE TABLE review_policy_presets (
    id          INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code        VARCHAR(32) NOT NULL UNIQUE,
    name        VARCHAR(64) NOT NULL,
    description VARCHAR(255),
    built_in    BOOLEAN NOT NULL DEFAULT FALSE
);

CREATE TABLE review_policy_preset_values (
    preset_id           INT NOT NULL REFERENCES review_policy_presets (id) ON DELETE CASCADE,
    state_id            INT NOT NULL REFERENCES states (id) ON DELETE CASCADE,
    base_interval_days  INT  NOT NULL CHECK (base_interval_days > 0),
    growth_factor       REAL NOT NULL CHECK (growth_factor > 0),
    max_interval_days   INT  NOT NULL CHECK (max_interval_days > 0),
    CHECK (max_interval_days >= base_interval_days),
    PRIMARY KEY (preset_id, state_id)
);

-- Per-user settings; one row per user, created lazily by the backend.
CREATE TABLE user_settings (
    user_id                 BIGINT PRIMARY KEY REFERENCES users (id) ON DELETE CASCADE,
    review_policy_preset_id INT REFERENCES review_policy_presets (id),
    notifications_enabled   BOOLEAN   NOT NULL DEFAULT TRUE,
    sound_effects_enabled   BOOLEAN   NOT NULL DEFAULT TRUE,
    daily_goal              INT       NOT NULL DEFAULT 10 CHECK (daily_goal BETWEEN 1 AND 100),
    review_time             TIME      NOT NULL DEFAULT '09:00',
    created_at              TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at              TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- ============ Preset seed data ============

INSERT INTO review_policy_presets (code, name, description, built_in) VALUES
    ('standard', 'Standard', 'Balanced intervals for steady retention.', TRUE),
    ('gentle',   'Gentle',   'Shorter intervals and lower caps — more frequent reviews.', TRUE),
    ('intense',  'Intense',  'Longer intervals and aggressive growth — fewer reviews once remembered.', TRUE);

INSERT INTO review_policy_preset_values (preset_id, state_id, base_interval_days, growth_factor, max_interval_days)
SELECT p.id, s.id, v.base, v.growth, v.max
FROM (VALUES
    ('standard', 'FORGOT',  1, 1.0,  1),
    ('standard', 'PARTIAL', 1, 1.0, 30),
    ('standard', 'REMEMBER',2, 2.0, 90),
    ('gentle',   'FORGOT',  1, 1.0,  2),
    ('gentle',   'PARTIAL', 1, 1.0, 14),
    ('gentle',   'REMEMBER',1, 1.5, 45),
    ('intense',  'FORGOT',  1, 1.0,  1),
    ('intense',  'PARTIAL', 2, 1.0, 45),
    ('intense',  'REMEMBER',3, 2.5, 180)
) AS v(preset_code, state_code, base, growth, max)
JOIN review_policy_presets p ON p.code = v.preset_code
JOIN states s ON s.code = v.state_code;
